
-- The first code is 20151125. 
-- After that, each code is generated by taking the previous one,
--  multiplying it by 252533, and then keeping the remainder from 
-- dividing that value by 33554393.
calc :: Int -> Int -> Int
calc n i = if i == 1 
           then n 
           else calc (mod (n * 252533) 33554393) (i-1)

getIndex :: Int -> Int -> Int
getIndex r c = sum [1..c]+sum(take (r-1) [c..])


main :: IO ()
main = do
  print $ calc 20151125 (getIndex 3010 3019) 